[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "development"

[cache]
  paths = ["node_modules/**", ".next/cache/**"]

[[plugins]]
package = "@netlify/plugin-nextjs"