#!/bin/bash
# This script generates TypeScript type definitions for the Storyblok components in the specified space.

# 1. Load the .env file and export all variables (only to current shell, hence the `set -a` and `set +a`)
set -a
source .env
set +a

# 2. Check if the required environment variables are set
if [ -z "$STORYBLOK_PERSONAL_ACCESS_TOKEN" ]; then
  echo "STORYBLOK_PERSONAL_ACCESS_TOKEN is not set. Please set it or update .env file."
  echo "Go to https://app.storyblok.com/#/me/account?tab=token to get your personal access token"
  exit 1
fi

if [ -z "$STORYBLOK_SPACE_ID" ]; then
  echo "STORYBLOK_SPACE_ID is not set. Please set it or update .env file."
  exit 1
fi

# 3. Login to Storyblok
npx storyblok logout
npx storyblok login --token ${STORYBLOK_PERSONAL_ACCESS_TOKEN} --region us

# 4. Pull the latest components from Storyblok
npx storyblok components pull --space ${STORYBLOK_SPACE_ID}

# 5. Generate TypeScript type definitions for the components
npx storyblok types generate \
  --space ${STORYBLOK_SPACE_ID} \
  --type-prefix Storyblok \
  --suffix ''

# 6. Remove the import of storyblok.d.ts from components file.
grep -v "^import .*['\"]\.\./storyblok\.d\.ts['\"];" .storyblok/types/${STORYBLOK_SPACE_ID}/storyblok-components.d.ts >tmp_components.d.ts

# 7. Remove the duplicated import lines and add the `storyblok.d.ts` content to the `storyblok-components.d.ts` file
awk '
  /^import / {
    if (!seen[$0]++) print $0
    next
  }
  { print $0 }
' .storyblok/types/storyblok.d.ts tmp_components.d.ts >.storyblok/types/${STORYBLOK_SPACE_ID}/storyblok-components.d.ts

# 8. Remove the temporary file
rm tmp_components.d.ts

# 9. Replace the `unknown` catch all types to `any` (FOR BACKWARDS COMPATIBILITY WITH STORYBLOKEDITABLE FUNCTION)
sed -i '' 's/\[k: string\]: unknown;/[k: string]: any;/g' .storyblok/types/${STORYBLOK_SPACE_ID}/storyblok-components.d.ts

# 10. Move the generated types file to `src/utils/storyblok-types.generated.ts`
cp .storyblok/types/${STORYBLOK_SPACE_ID}/storyblok-components.d.ts src/utils/storyblok-types.generated.ts

# 11. Remove the temporary storyblok dir, this is generated by `types generate` and is not needed after the types are generated
rm -rf .storyblok
